error: [vec_set] Index out of bounds
